### ISSUE TITLE
search icon appears indefinitely when searching for a set (that I assume does not exist)

### ISSUE THREAD

**Issue by navjanar1** [quickeducation/final-project#23]
When I search for "navjanar" in the section where I need to input "problem set link", it just constantly searches (showing search circle) and does not take me to any other page for many minutes. I did not create any problem sets yet, but attempted to search for one.

**Comment by zachp98** [comment]
Fixed in https://github.com/quickeducation/final-project/blob/master/project/src/Components/AnswerProblemSet.js line 76
