### ISSUE TITLE
Deleting 

### ISSUE THREAD

**Issue by emilytao19** [quickeducation/final-project#24]
Deleting user gives an error

**Comment by emilytao19** [comment]
<img width="1102" alt="Screen Shot 2019-06-10 at 3 58 39 PM" src="https://user-images.githubusercontent.com/32439428/59232368-e1237d00-8b98-11e9-90df-8e842e867d75.png">

**Comment by emilytao19** [comment]
1. Create a new user
2. Navigate to My Account
3. Click delete account
4. See error message

**Comment by zachp98** [comment]
Fixed in https://github.com/quickeducation/final-project/blob/master/project/src/Components/Firebase/Firebase.js line 122
