### ISSUE TITLE
Signing up

### ISSUE THREAD

**Issue by VeronicaChang** [quickeducation/final-project#27]
I signed up twice using the same email and there was an alert saying that the email has already been used by another account, but the website allowed me to proceed. The alert should stop the website from allowing an email from creating multiple accounts and accessing information.

**Comment by VeronicaChang** [comment]
1) Navigate to "Sign up"
2) Input email e.g. Bob@gmail.com and password
3) Refresh the page 
4) Input same email again
5) There will be an alert message but still allow you to enter the website

**Comment by zachp98** [comment]
Multiple team members have tried to reproduce this bug but we were unsuccessful. When we try to refresh, it just resets the field. Trying to register with an account that already exists throws an error. I am closing this unless there can be a 100% way to reproduce this bug.
