### ISSUE TITLE
Problem set entries does not account for only white space entries.

### ISSUE THREAD

**Issue by matthewkli97** [quickeducation/final-project#28]
Data validation when writing questions does not account for just 'whitespace' inputs. This allows for 'blank' entries to be added to the problem set. 

<img width="1680" alt="Screen Shot 2019-06-10 at 4 22 46 PM" src="https://user-images.githubusercontent.com/26758656/59233186-53499100-8b9c-11e9-8046-9ddfb7de5e01.png">

**Comment by zachp98** [comment]
This is a design decision to allow all characters in the input as long as the amount of characters is > 1 and < 120, not a failure.
