### ISSUE TITLE
Minor: Try again button clickable area is much bigger than the button

### ISSUE THREAD

**Issue by maps101** [quickeducation/final-project#30]
After completing a set and reviewing missed answers, the user can click at the center of the page and still go to try again. The link is much larger than the button shape.

To reproduce:
1. Complete any set
2. Select "Review Missed Qs"
3. Hover over space below answers and click anywhere between the question start and the try again button.

![test](https://user-images.githubusercontent.com/35041191/59240247-99145280-8bb8-11e9-9438-6178e360142d.gif)

**Comment by zachp98** [comment]
Fixed in https://github.com/quickeducation/final-project/blob/master/project/src/Components/ReviewProblemSet.js line 76
