### ISSUE TITLE
Problem Set ID

### ISSUE THREAD

**Issue by yiranni** [quickeducation/final-project#32]
- Not sure about what the Problem Set ID is when the first time using the site.
- Due to the confusion above, I clicked "Go" without typing any IDs. The site keeps loading but does not give me feedbacks as following.
 
![image](https://user-images.githubusercontent.com/32496771/59244192-52c6ef80-8bc8-11e9-85c4-2d34c63c8d78.png)

- Maybe it would be better to provide an error notice if the ID input is empty to the user, or tells the user what this means.

**Comment by zachp98** [comment]
Duplicate with #23
