### ISSUE TITLE
Delete question

### ISSUE THREAD

**Issue by s21dy** [quickeducation/final-project#35]
This may be more like a design decision.
I think it will really helpful if you allow the user to delete question if they accidentally add one more question set like the picture.  
![Screen Shot 2019-06-10 at 10 39 49 PM](https://user-images.githubusercontent.com/43624825/59246273-ae957680-8bd0-11e9-9ec6-33eb77e6fe12.png)

**Comment by zachp98** [comment]
This is a design decision, we wanted to just have the ability to add new questions to the set.
