### ISSUE TITLE
Correct Answers Marked As Wrong

### ISSUE THREAD

**Issue by charlyecastro** [quickeducation/final-project#37]
### The Grading Is Case Sensitive
It's probably for the best that you are not this strict with grading

### Steps to Recreate 
1. Create Problem Set with Capitalized Solution
2. Submit Non-Capitalized Response

<img width="1239" alt="Screen Shot 2019-06-10 at 11 07 26 PM" src="https://user-images.githubusercontent.com/24886389/59247668-f4ecd480-8bd4-11e9-9977-41fc19f844ac.png">
<img width="1241" alt="Screen Shot 2019-06-10 at 11 08 44 PM" src="https://user-images.githubusercontent.com/24886389/59247671-f74f2e80-8bd4-11e9-9f15-f45e98dbf43c.png">

**Comment by zachp98** [comment]
We want to ensure that the user enters the exact answer, as that will create the most straightforward experience. We do not believe that this issue causes a major flaw in the core functionality of the app.
