### ISSUE TITLE
Changing display name gives error

### ISSUE THREAD

**Issue by clairehjk** [quickeducation/final-project#40]
"Connection Error, try refreshing your page." when trying to assign a blank display name. This case should be handled properly. 

To recreate:
1. Sign up
2. Go to My account
3. Edit display name
4. leave the display name blank 
5. Shows loading icon and an alert: "Connection Error, try refreshing your page."
6. Clicking Ok leaves you back to Editing display name page.

**Comment by zachp98** [comment]
Fixed in https://github.com/quickeducation/final-project/blob/master/project/src/Components/MyAccount.js line 84
