### ISSUE TITLE
Have to click "Submit Answer" twice 

### ISSUE THREAD

**Issue by navjanar1** [quickeducation/final-project#43]
1. Search for your problem set
2. Answer question(s)
3. Click "Submit Answers"
Remains at the same page
4. Click "Submit Answers" again
Then it goes to the next page, but it should happen the first time the button is clicked

**Comment by zachp98** [comment]
When using the steps above, I created my own problem set with multiple questions, used the link to access it, and submitted my answers. I tested this with all questions answered correctly, some correctly, and non correctly. I was able to reach the "Finished" page every time with only one click. This might be related to user error, and thus is not a real failure of our app.
