### ISSUE TITLE
Hard to read text

### ISSUE THREAD

**Issue by navjanar1** [quickeducation/final-project#44]
1. Search for your problem set
2. Answer question(s)
3. Click "Submit Answers"
4. Click "Submit Answers" again
5. Click "Review Missed Q's"
The "Try Again" text in the green text is very hard to read
![Screen Shot 2019-06-11 at 2 38 36 AM](https://user-images.githubusercontent.com/37914670/59261641-b7973f80-8bf2-11e9-9a4c-f3569c921125.png)

**Comment by zachp98** [comment]
We do not believe that this is an issue with the core functionality of our app.
