### ISSUE TITLE
Get past unique constraints with space

### ISSUE THREAD

**Issue by bbalansay** [quickeducation/final-project#46]
You are not allowed to create duplicate usernames when changing your username under Account, but adding a space to the end of the name allows you to get around that. There are currently two "emails".

**Comment by zachp98** [comment]
Our requirements allow any UTF-8 characters in a username if the username is over 1 character in length and less than 60. Even as it might create some visual confusion, all usernames will be unique regardless of their spaces, and so we believe that this is more of a design concern than a real failure with the core functionality of the project.
