### ISSUE TITLE
Problem set blank answers

### ISSUE THREAD

**Issue by rioishii** [quickeducation/final-project#48]
When a user does not know the answer to the question in a problem set, they are not allowed to submit answers if they have a blank answer. This would be a minor user experience issue.  

Reproduction steps:
1. Create account
2. Create problem set
3. Submit set
4. Test yourself
5. Submit test without any answers
6. Dialog pops up saying answer length is invalid

**Comment by zachp98** [comment]
It is in our design to force the user to answer each question, that way the problem set stays atomic and the problem sets are treated as whole entities. Since this is a design question more than a concern with the core functionality of the app, we do not believe this is a real failure.
