### ISSUE TITLE
No way to delete a question

### ISSUE THREAD

**Issue by JessicaXLou** [quickeducation/final-project#51]
![image](https://user-images.githubusercontent.com/32353106/59308633-66b93280-8c56-11e9-987f-192bd2708fb6.png)
There is no way to delete a question when creating a problem set, and it won't let me create the problem set because there is an empty row. If I were to accidentally click on "New Question" there is no way to fix it I would have to make another question.
![image](https://user-images.githubusercontent.com/32353106/59308726-95370d80-8c56-11e9-9590-f215b233d17d.png)

**Comment by zachp98** [comment]
This is part of our design and our requirements, we want to make problem set creation atomic so that the user can only add valid questions and answers to this set. As part of our MVP, this is not an issue with the core functionality as defined by our requirements.
