### ISSUE TITLE
Those on leaderboard that tie get left out

### ISSUE THREAD

**Issue by JessicaXLou** [quickeducation/final-project#52]
![image](https://user-images.githubusercontent.com/32353106/59308868-fbbc2b80-8c56-11e9-9909-22b4ca20c5d3.png)
I have a score of 1 but I am not on the leaderboard. Ties end up leaving some users out of the leaderboard.

**Comment by zachp98** [comment]
Even as this issue was marked as major, we don’t believe that this is an issue that requires to be fixed in order to ensure the integrity and functionality of our application. 
    Our database will pull the top 10 scoring users for the leaderboard, with ties being broken by the database ordering of the user IDs. This is consistent with our requirements. In order for the current user to always be shown in the leaderboard, there can be one of two changes. One, the user will always show up at the top of the list of ties. This might work, but would require a large refactoring of our database pull function that would take more time then we have, especially since we would have to do comprehensive testing on every other part of the application that uses the database to ensure that nothing else was broken in the process. Two, the leaderboard could be expanded beyond just 10 users to allow for all of the ties to show up. This would go against our requirements of only 10 people and would create issues if there were many ties, since the leaderboard could be expanded greatly. We wouldn’t want to combine scores into one line for each score either, since the point of the leaderboard is to be able to see each person and their achievement.
    This issue arises mostly from this small beta testing environment, since many people are only going to test the problem set once and all have 1 point. In a real published app, there would be widely different scores and the scores would change much more rapidly. This would rapidly decrease the chance that there are too many ties at the top of the leaderboard and would reduce the problems of this issue.
Lastly, if we did choose to not create a fix for this issue, the user will still always be able to see their score in the ‘My Account’ page if they want to check it. There is no inherent loss of data and all of our requirements will still be met.
    Given these reasons, we do not believe that the issue would be feasible and reasonable to fix in our narrow timeframe.
