### ISSUE TITLE
Submitting a URL for problem set ID crashes the app completely

### ISSUE THREAD

**Issue by vincentmvdm** [quickeducation/final-project#53]
If a user submits a URL for the example ID and presses "Go", the app ends up on a blank screen and, in other words, crashes completely. This is not a duplicate of past search issues as there is no loading indicator or any feedback really.

Steps to reproduce:
1. Go to https://quickeducation442.firebaseapp.com/
2. Paste in the app's URL (https://quickeducation442.firebaseapp.com/) or any URL into the search box
3. Notice how the app goes to a blank screen and does not display the usual loading spinner and/or error

**Comment by zachp98** [comment]
Fixed in https://github.com/quickeducation/final-project/blob/master/project/src/Components/AnswerProblemSet.js line 61
