### ISSUE TITLE
Refreshing a page causes users to get redirected

### ISSUE THREAD

**Issue by vincentmvdm** [quickeducation/final-project#54]
As a user, I want to be able to refresh a page. One of the use cases is resetting my inputs and starting from a blank slate while I am creating a problem set. However, refreshing any page causes users to be redirected to https://quickeducation442.firebaseapp.com/. That is a UX issue.

Steps to reproduce:

1. Open the app
2. Navigate to https://quickeducation442.firebaseapp.com/createset
3. Refresh the page (CMD + R) to, for instance, get a fresh problem set
4. Notice how the app forgets your location and puts you back at https://quickeducation442.firebaseapp.com/

**Comment by MatthewSVogt** [comment]
Issue resolved withhttps://github.com/quickeducation/final-project/commit/068bb2b06150367a08f8e78fd55fb3f7f9b20cc5. Variable added to session to wait for auth object initialization.
